### ISSUE TITLE
Existence of types.py file

### ISSUE THREAD

**Issue by mcopik** [flozz/pypapi#19]
Hi!

While trying to add a new function to pypapi API that happens to be quite useful for me, I stumbled on an unusual error when trying to rebuild the interface after modifying `papi.h`. Running `python pypapi/papi_build.py` ends with an error:

```python
Traceback (most recent call last):
  File "/home/mcopik/software/python_papi/env/lib/python3.5/site-packages/cffi/cparser.py", line 5, in <module>
    from . import _pycparser as pycparser
ImportError: cannot import name '_pycparser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pypapi/papi_build.py", line 10, in <module>
    ffibuilder = FFI()
  File "/home/mcopik/software/python_papi/env/lib/python3.5/site-packages/cffi/api.py", line 65, in __init__
    from . import cparser
  File "/home/mcopik/software/python_papi/env/lib/python3.5/site-packages/cffi/cparser.py", line 7, in <module>
    import pycparser
  File "/home/mcopik/software/python_papi/env/lib/python3.5/site-packages/pycparser/__init__.py", line 14, in <module>
    from subprocess import check_output
  File "/usr/lib/python3.5/subprocess.py", line 364, in <module>
    import signal
  File "/usr/lib/python3.5/signal.py", line 3, in <module>
    from functools import wraps as _wraps
  File "/usr/lib/python3.5/functools.py", line 22, in <module>
    from types import MappingProxyType
ImportError: cannot import name 'MappingProxyType'
```

Looking at [mailing list discussion](https://mail.python.org/pipermail/python-ideas/2015-November/037077.html) and a [StackOverflow answer](https://stackoverflow.com/questions/43453414/cannot-import-name-mappingproxytype-error-after-importing-functools), the problem might be in the existence of file called `types.py`. I'm not sure why this happened right now but the problem is gone after changing the file name. Is it possible that the header files was modified last time before `types.py` was created?

**Comment by flozz** [comment]
fix released in **v5.5.1.5** :)
