### ISSUE TITLE
PapiComponentError: Not supported by component for custom function

### ISSUE THREAD

**Issue by pavaninguva** [flozz/pypapi#34]
Hi! Cool package! 

I wrote a custom function and was trying to estimate the number of flops during execution

```
from pypapi import papi_high
from pypapi import events as papi_events

papi_high.start_counters([papi_events.PAPI_FP_OPS])
foo
x1 = papi_high.stop_counters()
print(x1)
```

However, i encountered the following error:
```
Traceback (most recent call last):
  File "/mnt/c/Users/Pavan/Projects/PBM_Schemes/Python/2D/Case1/time.py", line 18, in <module>
    papi_high.start_counters([papi_events.PAPI_FP_OPS,])
  File "/home/pavan/miniconda3/envs/pyclaw/lib/python3.10/site-packages/pypapi/exceptions.py", line 170, in papi_error_wrapper
    raise object_()
pypapi.exceptions.PapiComponentError: Not supported by component. (PAPI_ECMP, PAPI_ESBSTR)
````

Would appreciate any help here! Thanks!

**Comment by flozz** [comment]
Hello,

You error comes from PAPI itself not from PyPAPI (this project is only a Python binding for the PAPI library). You may get some help from PAPI developers: https://icl.utk.edu/papi/custom/index.html?lid=50&slid=67

:)
