### ISSUE TITLE
Latest release (5.5.1.6) fails with PapiNoEventError: Event does not exist. (PAPI_ENOEVNT)

### ISSUE THREAD

**Issue by itamarst** [flozz/pypapi#40]
This is Ubuntu 22.04 on Linux 6.5.6.

```
Python 3.11.7 (main, Dec  8 2023, 18:56:58) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypapi import papi_high
>>> papi_high.ipc()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/itamarst/devel/sandbox/venv311/lib/python3.11/site-packages/pypapi/exceptions.py", line 197, in papi_error_wrapper
    raise object_()
pypapi.exceptions.PapiNoEventError: Event does not exist. (PAPI_ENOEVNT)
```

Same problem with 5.5.1.5.

**Comment by flozz** [comment]
Hello,

This can be caused because some events are not available / supported on all CPU.

Anyway, this is most probably not a bug related to the Python bindings but to the PAPI library itself. Please report it upstream :)
